#!/usr/bin/env groovy
@Library('evenOdd') _
import Properties
import DB

//def _CTC_DB_VERSION
def ORACLE_TNS
def msteamsMessage=[ ]


node('CI') {
    // Node to build
//    agent {node {label 'Main'} }


    properties([
            disableConcurrentBuilds(),
            parameters([
                    gitParameter(
                            branch: 'master',
                            branchFilter: '.*',
                            defaultValue: '',
                            description: 'Test branches',
                            name: 'API_GIT_BRANCH',
                            quickFilterEnabled: false,
                            selectedValue: 'NONE',
                            sortMode: 'DESCENDING',
                            tagFilter: '*',
                            type: 'PT_BRANCH',
                            useRepository: Properties.Git.API_URL,
                            listSize: '15'
                    ),
                    choice(
                            name: 'ENVIRONMENT',
                            choices: DB.envList(),
                            description: DB.envDescription()
                    )

            ])
    ])

 //    try {
         stage('checkout') {
           gitCheckout(API_GIT_BRANCH, Properties.Git.API_CRED_ID, Properties.Git.API_URL)
         }
         stage('get env vars') {

             (ORACLE_TNS) = DB.envList(ENVIRONMENT)

         }
         // On this stage, script difference_db.cmd compare database difference and generate a report in the text file.
         stage('Compare Database Difference') {

             echo 'Comparing Database Difference...'

             withCredentials([
                     string(credentialsId: 'CI_DB_PMC_SYSTEM_PASSW', variable: 'CI_DB_PMC_SYSTEM_PASSW')

             ])

                     {
                         dbUtils.createReport(ORACLE_TNS, CI_DB_PMC_SYSTEM_PASSW)
                                              }
             script {def _CTC_DB_VERSION = println bat(script:"cd Scripts\\difference_db\\ && set _CTC_DB_VERSION && difference_db.cmd ${ORACLE_TNS} sqlsql", returnStdout:true)
                 println("file_name = ${_CTC_DB_VERSION}")}
             echo 'Compared Database Difference!'


         }
         // On this stage, mvn wagon:upload-single plugin upload report to Nexus.
         stage('Upload Report to Nexus') {

             echo 'Uploading Report to Nexus...'

             msteamsMessage += promoteRawJob(Properties.RawArtifact.DIFFERENCE_DB, Properties.RawArtifact.DIFFERENCE_DB.code)

             echo 'Uploaded Report to Nexus!'

         }
//         currentBuild.result = 'SUCCESS'
//     } catch (Exception err) {
//         println "Error: ${err}"
//         currentBuild.result = 'FAILURE'
//     } finally {
//         switch (currentBuild.result) {
//             case 'SUCCESS':
//                 mailNotify(
//                     "${_CTC_DB_VERSION}"
//                 )
////                 msteamsNotify.success("Build success")
//                 break
//             case 'FAILURE':
////                 msteamsNotify.fail("Build failed")
//                 break
//             default:
//                 break
//         }
//     }

    // Send email notification.
    post {

         success {
            echo 'Sending email notification...'
             mailNotify(
                     "${_CTC_DB_VERSION}"

             )
             echo 'Email notification sent!'
        }
    }


}